-- 코드를 입력하세요
SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN (
SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY DATETIME
LIMIT 3

# # JOIN 사용 x
# SELECT NAME, DATETIME FROM ANIMAL_INS A
# WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
# ORDER BY DATETIME LIMIT 3
# # JOIN 사용
# SELECT A.NAME, A.DATETIME FROM ANIMAL_INS A
# LEFT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
# WHERE B.ANIMAL_ID IS NULL
# ORDER BY A.DATETIME LIMIT 3