-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM DOCTOR D JOIN APPOINTMENT A ON D.DR_ID = A.MDDR_ID
JOIN PATIENT P ON P.PT_NO = A.PT_NO
WHERE DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13' 
AND D.MCDP_CD = 'CS'
AND A.APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD ASC