-- 코드를 입력하세요
# SELECT DISTINCT A.CAR_ID
# FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
# ON A.CAR_ID = B.CAR_ID
# WHERE A.CAR_TYPE = '세단'
# AND MONTH(B.START_DATE) = 10
# ORDER BY A.CAR_ID DESC

SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
SELECT CAR_ID FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = '세단')
AND MONTH(START_DATE) = 10
ORDER BY CAR_ID DESC